name: Update authored actions badges

on:
  workflow_dispatch:
  schedule:
    # Run once daily at 6 AM UTC
    - cron: '0 6 * * *'

concurrency:
  group: badges-repo-updates
  cancel-in-progress: false

jobs:
  update-authored-actions-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout badges repository
      uses: actions/checkout@v5

    - name: Count authored GitHub Actions
      id: actions-count
      uses: actions/github-script@v7
      with:
        script: |
          // Search for GitHub Actions repositories
          const searchQuery = 'topic:github+topic:actions+user:joshjohanning+fork:true';
          console.log(`\nSearching for repositories with query: ${searchQuery}`);
          
          let allRepos = [];
          let page = 1;
          let hasMore = true;
          
          while (hasMore) {
            const searchResult = await github.rest.search.repos({
              q: searchQuery,
              per_page: 100,
              page: page
            });
            
            allRepos = allRepos.concat(searchResult.data.items.map(item => item.full_name));
            
            if (searchResult.data.items.length < 100) {
              hasMore = false;
            } else {
              page++;
            }
          }
          
          console.log('\nFound repositories from GitHub search:');
          allRepos.forEach(repo => console.log(`  - ${repo}`));
          
          const actionCount = allRepos.length;
          console.log(`\nTotal authored actions count: ${actionCount}`);
          core.setOutput('count', actionCount);

    - name: Update badge data
      run: |
        # Use the actual count from the previous step
        ACTIONS_COUNT="${{ steps.actions-count.outputs.count }}"
        echo "Updating authored actions badge with count: $ACTIONS_COUNT"
        
        # Create the JSON file for the authored actions dynamic badge
        mkdir -p authored-actions
        cat > authored-actions/action-count.json << EOF
        {
          "schemaVersion": 1,
          "label": "authored actions",
          "message": "$ACTIONS_COUNT",
          "labelColor": "333",
          "color": "blue",
          "namedLogo": "github"
        }
        EOF
        
        # Commit and push if changed
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add authored-actions/action-count.json
        if git diff --staged --quiet; then
          echo "No changes to badge data - authored actions count is still $ACTIONS_COUNT"
        else
          echo "Changes to commit and push"
          git commit -m "ci: update authored actions badges"
          git push
        fi
