name: Update Script Count Badge

on:
  repository_dispatch:
    types: [update-script-count]
  workflow_dispatch:
  schedule:
    # Run every 12 hours at midnight and noon UTC
    - cron: '0 0,12 * * *'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout badges repository
      uses: actions/checkout@v5

    - name: Checkout github-misc-scripts repository
      uses: actions/checkout@v5
      with:
        repository: joshjohanning/github-misc-scripts
        path: github-misc-scripts

    - name: Count scripts in gh-cli folder
      id: count
      run: |
        # Count .sh files in gh-cli directory
        script_count=$(find github-misc-scripts/gh-cli -name "*.sh" -type f | wc -l)
        echo "Script count: $script_count"
        echo "count=$script_count" >> $GITHUB_OUTPUT
        
    - name: Update badge data
      run: |
        # Use the actual count from the previous step
        SCRIPT_COUNT="${{ steps.count.outputs.count }}"
        echo "Updating badge with script count: $SCRIPT_COUNT"
        
        # Create the JSON file for the dynamic badge
        cat > github-misc-scripts-gh-cli-count.json << EOF
        {
          "schemaVersion": 1,
          "label": "gh-cli scripts",
          "message": "$SCRIPT_COUNT",
          "color": "brightgreen",
          "namedLogo": "github"
        }
        EOF
        
        # Commit and push if changed
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add github-misc-scripts-gh-cli-count.json
        if git diff --staged --quiet; then
          echo "No changes to badge data - count is still $SCRIPT_COUNT"
        else
          echo "Changes to commit and push"
          git commit -m "Update gh-cli script count badge"
          git push
        fi
